#services:
#  postgres:
#    image: postgres:16
#    container_name: mini-shopify-postgres
#    environment:
#      POSTGRES_DB: minishopify
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#volumes:
#  postgres-data:
spring:
  application:
    name: mini-shopify

  datasource:
    url: jdbc:h2:file:./data/minishopify
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080