### Invalid Register Merchant
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "fullName": "Sheena McCarthy",
  "email": "sheena@fountains.com",
  "password": "password123"
}

### Login Merchant
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "sheena@fountains.com",
  "password": "password123"
}

### Create Store
POST http://localhost:8080/api/stores?ownerId=1
Content-Type: application/json

{
  "storeName": "Alice Fashion",
  "description": "Modern fashion store"
}

### Create Product
POST http://localhost:8080/api/stores/1/products
Content-Type: application/json

{
  "name": "Classic Hoodie",
  "description": "Heavyweight cotton hoodie",
  "price": 59.99,
  "stockQuantity": 25,
  "imageUrl": "https://share.google/aVVJO7JTYCFlyeYf9"
}

### List Store Products
GET http://localhost:8080/api/stores/1/products

### Get Product
GET http://localhost:8080/api/stores/1/products/1

### Update Product
PUT http://localhost:8080/api/stores/1/products/1
Content-Type: application/json

{
  "name": "Premium Classic Hoodie",
  "description": "Premium heavyweight cotton hoodie",
  "price": 69.99,
  "stockQuantity": 20,
  "imageUrl": "https://example.com/premium-hoodie.jpg"
}

### Delete Product
DELETE http://localhost:8080/api/stores/1/products/1

### Public Storefront
GET http://localhost:8080/api/public/stores/alice-fashion